[package]
name = "nbody"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

# [features]
# gpu = []

[dependencies]
num-traits = "0.2.19"
paste = "1.0.15"
rand = "0.9.0"


[target.'cfg(target_arch = "wasm32")'.dependencies]
