[package]
name = "nbody"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# [features]
# gpu = []

[dependencies]
num-traits = "0.2.19"


[target.'cfg(target_arch = "wasm32")'.dependencies]
